### ISSUE TITLE
asn.py uses ip4r() and ip4r_size()

### ISSUE THREAD

**Issue by pjessen** [openSUSE/mirrorbrain#63]
These functions are now called iprange() and iprange_size().  See https://progress.opensuse.org/issues/62678#note-4

**Comment by ott** [comment]
@pjessen If I understand issue [62678](https://progress.opensuse.org/issues/62678#note-4) correctly, the issue has been resolved and mod_asn is not used anymore. If so, can you please close this issue?

**Comment by pjessen** [comment]
In principle, the problem still exists in mirrorbrain, but afaiu, we're not using mirrorbrain anymore. I guess nobody cares much, so I'll close.
